### ISSUE TITLE
Does it still work with obfuscated and minified code ?

### ISSUE THREAD

**Issue by ghost** [alonrbar/peppermint-di#5]
I am reading the last comment on [here](https://stackoverflow.com/a/20058395/5380904) and its says : 

>Most code these days is minified and obfuscated. Since this code is based on argument names, which are a target of minification, this code will not hold up on such post processing practices.

It took me some time to understand what that meant and I think they are right . Can you please confirm ?

**Comment by alonrbar** [comment]
As it is with any good question, the answer is - it depends.

If you are using peppermint-di with TypeScript everything will work as expected, even when using minifcation and obfuscation (if you're not yet using typescript I highly recommend it, regardless of this specific subject).

If you are using peppermint-di with plain JavaScript then yes, minification and obfuscation can cause problems. The solution in this case is to configure your bundler (I'm guessing you're using one of the major bundlers like webpack, rollup or parcel) to preserve argument names. For instance, if you're using webpack you should disable the `mangle` option of the minimizer - see [here](https://webpack.js.org/plugins/terser-webpack-plugin/#terseroptions) and [here](https://github.com/terser/terser#minify-options) (I may be missing some other configurations necessary since it has been a while since I developed in plain javascript but you get the idea).

**Comment by ghost** [comment]
@alonrbar 

>If you are using peppermint-di with TypeScript everything will work as expected, even when using minifcation and obfuscation

Why would it work with TS and not with JS ? Can you pls elborate ? As far as I understand for both someone would have to do what you suggested : 

>The solution in this case is to configure your bundler ... to preserve argument names.

**Comment by alonrbar** [comment]
When using typescript with the `experimentalDecorators` and `emitDecoratorMetadata` [compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) set to true in the [tsconfig file](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) typescript will emit relevant type metadata that can be used in runtime to detect function argument types, regardless of minimization and obfuscation. 

If you are interested in the mechanics of how such thing works you can checkout the source of the [i decorator](https://github.com/alonrbar/peppermint-di/blob/master/src/i.ts) from this package. If you want to learn more about decorators in typescript and how they work you can start [here](https://www.typescriptlang.org/docs/handbook/decorators.html).

Do note however that typescript will only emit this metadata if a class is decorated with at least one decorator. This is why the `@injectable` decorator in this package was created (in fact the injectable decorator has an [empty implementation](https://github.com/alonrbar/peppermint-di/blob/master/src/injectable.ts) since typescript only care if there is a decorator used, not what it actually does).

For usage examples with both typescript and javascript please check the readme file.
